#!/bin/bash
#populate our variables from the arguments
paramslist=$@
operationmode=$1
params=""

#function pingcheck
#ping a device to see if it is up
function pingcheck
{
  ping=`ping -c 1 $host | grep bytes | wc -l`
  if [ "$ping" -gt 1 ]; then
    echo "$host is up";
  else
    echo "$host is down quitting";
    exit
  fi
}

#functiom portcheck
#test a port to see if it is open
function portcheck
{
  for((counter=$startport; counter<=$stopport; counter++))
  do
    (echo >/dev/tcp/$host/$counter) > /dev/null 2>&1 && echo "$counter open"
  done
}

#main function
function main
{
i=0
#params

for word in $paramslist
do
        #echo $word
        params[i]=$word
        i=$[$i+1]
done

case "$operationmode" in
        "-Sa")  host=${params[1]}
		startport=${params[2]}
		stopport=${params[3]}
		echo "OPERATION MODE: $operationmode"
                echo "HOST: $host"
                echo "PORT START: $startport"
                echo "PORT STOP: $stopport"
                pingcheck
                portcheck;;

	"-Ma") 	startport=${params[${#params[@]}-2]}
		stopport=${params[${#params[@]}-1]}
		for((count=1;count<${#params[@]}-2;count++));
		do
	       		host=${params[count]}
			echo "SCANING $host ..."
			pingcheck
			portcheck
		done;;

	"-h") 	echo "Sintaxe: [operation mode] [options mode] [options arguments]"
		echo "OPERATION MODE:"
		echo "	-Sa options_mode options_arguments -> perform scan over a single ip address"
		echo "	-Ma options_mode options_arguments -> perform scan over multiples address ip"
		echo "OPTIONS MODE:"
		echo "	-Sa [IP_ADDRESS_TO_SCAN] options_arguments"
		echo "	-Ma [IP_ADDRESS_TO_SCAN_1 ... IP_ADDRESS_TO_SCAN_n] [options_arguments]"
		echo "OPTIONS ARGUMENTS:"
		echo "	[start_port stop_port] ";;

        *) echo "UNKNOOW OPERATION MODE, TYPE -h FOR HELP";;
esac

}

#run our functions
main

