#!/bin/bash
#populate our variables from the arguments
paramslist=$@
operationmode=$1

#function pingcheck
#ping a device to see if it is up
function pingcheck
{
  ping=`ping -c 1 $host | grep bytes | wc -l`
  if [ "$ping" -gt 1 ]; then
    echo "$host is up";
  else
    echo "$host is down quitting";
    exit
  fi
}

#functiom portcheck
#test a port to see if it is open
function portcheck
{
  for((counter=$startport; counter<=$stopport; counter++))
  do
    (echo >/dev/tcp/$host/$counter) > /dev/null 2>&1 && echo "$counter open"
  done
}

#main function
function main
{
i=0
params=""

for word in $paramslist
do
        #echo $word
        params[i]=$word
        i=$[$i+1]
done

case "$operationmode" in
        "-Sa")  host=${params[1]}
		startport=${params[2]}
		stopport=${params[3]}
		echo "OPERATION MODE: $operationmode"
                echo "HOST: $host"
                echo "PORT START: $startport"
                echo "PORT STOP: $stopport"
  echo ${params[0]}
                pingcheck
                portcheck;;
        *) echo "UNKNOOW OPERATION MODE";;
esac

}

#run our functions
main

